name: Graphviz CI
on: [push]
jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Test
      run: yarn start
